import { readFile } from "node:fs/promises";
import { join } from "node:path";

function assertIncludes(content: string, expected: string, message: string) {
  if (!content.includes(expected)) {
    throw new Error(`${message}: missing "${expected}"`);
  }
}

function assertNotIncludes(content: string, unexpected: string, message: string) {
  if (content.includes(unexpected)) {
    throw new Error(`${message}: unexpected "${unexpected}"`);
  }
}

const prompt = await readFile(join(process.cwd(), "src/prompts/business-prompt.md"), "utf-8");

assertIncludes(prompt, "已核实接口逻辑", "business prompt should require definite answers when interface logic is verified");
assertIncludes(prompt, "不要使用“可能原因”“最可能原因”", "business prompt should avoid weak headings for verified conclusions");
assertIncludes(prompt, "不确定性只能保留在未核实的枚举含义、外部状态或用户未提供的数据上", "business prompt should scope uncertainty");
assertIncludes(prompt, "代码事实提取类问题", "business prompt should generalize direct code fact extraction");
assertIncludes(prompt, "权限码、按钮编码、配置值、枚举值、接口路径、字段名", "business prompt should cover common direct facts");
assertIncludes(prompt, "直接提取并回答证据中的原值", "business prompt should require extracting values from evidence");
assertIncludes(prompt, "编码语义并列输出", "business prompt should require code and semantic meaning together");
assertIncludes(prompt, "枚举值、常量值、状态值、类型值、数据库字段编码或数字字典值", "business prompt should cover enum constants and database code values");
assertIncludes(prompt, "必须继续核实对应语义", "business prompt should require resolving semantic meaning");
assertIncludes(prompt, "结果必须同时包含编码和值对应的语义", "business prompt should include both code and meaning");
assertIncludes(prompt, "语义未核实时，不得只输出数字或编码", "business prompt should not output code alone when meaning is unknown");
assertIncludes(prompt, "不要把已命中的事实改写成泛化建议", "business prompt should avoid generic advice after direct evidence");
assertIncludes(prompt, "证据不足或证据冲突类问题", "business prompt should handle insufficient or conflicting evidence");
assertIncludes(prompt, "不同问法命中不同候选流程、不同仓库或相反结论", "business prompt should detect inconsistent evidence from query variants");
assertIncludes(prompt, "不得选择看起来更合理的一边作答", "business prompt should forbid guessing between conflicting candidates");
assertIncludes(prompt, "目标范围一致性", "business prompt should require evidence to match the requested project scope");
assertIncludes(prompt, "字段注释不能替代目标项目代码枚举", "business prompt should not answer project enum questions from unrelated db comments");
assertIncludes(prompt, "用户指定项目、端、模块、技术栈、接口、页面或业务入口", "business prompt should generalize project-scoped evidence requirements");
assertIncludes(prompt, "递进式查找", "business prompt should require progressive evidence discovery");
assertIncludes(prompt, "不可或缺条件", "business prompt should distinguish required evidence from auxiliary clues");
assertIncludes(prompt, "候选线索", "business prompt should mark db comments and similar fields as clues only");
assertIncludes(prompt, "直接读写、映射、返回、校验、配置读取或调用链", "business prompt should require binding evidence before answering enum facts");
assertIncludes(prompt, "请补充项目、仓库、入口、页面、单号、环境或业务场景", "business prompt should guide user to refine the question");
assertIncludes(prompt, "明确锚点优先", "business prompt should prefer precise anchors before broad search");
assertIncludes(prompt, "接口路径、接口名、方法名、类名、表名、字段名、配置 key、错误文案", "business prompt should list precise anchor types");
assertIncludes(prompt, "先做精确命中", "business prompt should require exact-match lookup first");
assertIncludes(prompt, "再补充语义扩展", "business prompt should use semantic expansion after exact anchors");
assertIncludes(prompt, "追问锚点继承", "business prompt should inherit anchors across follow-up questions");
assertIncludes(prompt, "前文已经确认项目、仓库、接口路径、入口文件、入口方法、类名、方法名或符号", "business prompt should identify prior confirmed anchors");
assertIncludes(prompt, "必须优先带着这些已确认锚点继续查", "business prompt should narrow follow-up searches with prior anchors");
assertIncludes(prompt, "不得重新放宽到其它项目、其它技术栈或宽泛业务词", "business prompt should not broaden follow-up search after anchors exist");
assertIncludes(prompt, "AddOrUpdateV1、/add-or-update/v1、WuLiuController、oa-stock", "business prompt should include representative anchor example");
assertIncludes(prompt, "逻辑梳理流程图规范", "business prompt should require flow diagrams for logic explanations");
assertIncludes(prompt, "企业微信可正常显示的 Markdown 文本流程图", "business prompt should use WeCom-compatible markdown flow diagrams");
assertIncludes(prompt, "不要依赖 Mermaid", "business prompt should avoid Mermaid for WeCom answers");
assertIncludes(prompt, "用缩进、编号、箭头和条件分支表达流程", "business prompt should define compatible flow syntax");
assertIncludes(prompt, "关键操作总结协议", "business prompt should require Claude Code style operation summaries");
assertIncludes(prompt, "一句话状态", "business prompt should require concise one-line operation updates");
assertIncludes(prompt, "继续核实中", "business prompt should indicate when background search continues");
assertIncludes(prompt, "不要使用固定四段模板", "business prompt should avoid verbose four-field templates");
assertIncludes(prompt, "读取需求、GitNexus 检索、代码片段核实、数据库查询、生产 SQL 等待用户执行、测试或部署验证", "business prompt should list key operation summary scenarios");
assertIncludes(prompt, "阶段性进度消息必须覆盖式表达", "business prompt should require overwrite-style progress updates");
assertIncludes(prompt, "不要把多轮检索状态连续追加成一长段", "business prompt should forbid appending many progress updates");
assertIncludes(prompt, "关键入口、接口路径、匹配项目", "business prompt should require key anchors in answers");
assertIncludes(prompt, "仓库或项目、入口文件或入口方法、接口路径或页面路由", "business prompt should require returned matched evidence anchors");
assertNotIncludes(prompt, "已做：", "business prompt should not use verbose operation summary action field");
assertNotIncludes(prompt, "得到：", "business prompt should not use verbose operation summary evidence field");
assertNotIncludes(prompt, "影响：", "business prompt should not use verbose operation summary impact field");
assertNotIncludes(prompt, "下一步：", "business prompt should not use verbose operation summary next-step field");
assertNotIncludes(prompt, "6e6", "business prompt should not hard-code a single permission value regression example");
assertIncludes(prompt, "SQL 输出前验证", "business prompt should require SQL validation before output");
assertIncludes(prompt, "SQL 参数前置", "business prompt should require SQL parameters first");
assertIncludes(prompt, "统一放在 SQL 最前面", "business prompt should put user parameters before SQL body");
assertIncludes(prompt, "需要你提供/填写：xxx、yyy、zzz", "business prompt should use one unified parameter sentence");
assertIncludes(prompt, "必须先在 dev 环境对应库执行同一条只读查询", "business prompt should require dev database validation");
assertIncludes(prompt, "查询不报错后才允许输出给用户", "business prompt should only output SQL after successful validation");
assertIncludes(prompt, "验证失败时不得输出为已验证 SQL", "business prompt should not claim failed SQL is verified");
assertIncludes(prompt, "生产 SQL 也必须先用 dev 对应库验证结构正确性", "business prompt should validate production SQL structure in dev first");
assertIncludes(prompt, "输出 `prod_sql_required.sql` 前", "business prompt should apply validation to human-loop production SQL");
assertIncludes(prompt, "dev 缺表例外", "business prompt should allow code inference when dev table is missing");
assertIncludes(prompt, "通过目标项目代码反推表名、字段", "business prompt should require code-based table inference");
assertIncludes(prompt, "dev 库无对应表，SQL 未做 dev 执行校验，已通过代码反推结构", "business prompt should label skipped dev validation");
assertIncludes(prompt, "可以通过目标项目代码反推表结构并跳过 dev 执行校验", "human loop SQL should allow missing dev table exception");
assertIncludes(prompt, "业务节点审核 TodoList", "business prompt should merge review todolist into business node");
assertIncludes(prompt, "最终回答前必须在业务节点内部完成以下 TodoList", "business prompt should require internal todolist review");
assertIncludes(prompt, "必须逐项勾选完成后才允许输出最终回答", "business prompt should require completing review todos");
assertIncludes(prompt, "不要把 TodoList 标题、勾选过程或逐项自检说明输出给用户", "business prompt should hide todolist process");
assertIncludes(prompt, "runtime_todolist_update", "business prompt should require runtime todolist tool");
assertIncludes(prompt, "不得只在文本里声明已完成", "business prompt should forbid text-only todolist completion");
assertIncludes(prompt, "project_scope_audited", "business prompt should require project scope audit item");
assertIncludes(prompt, "sql_correctness_audited", "business prompt should require SQL audit item");
assertIncludes(prompt, "evidence_audited", "business prompt should require evidence audit item");
assertIncludes(prompt, "owner_contact_audited", "business prompt should require owner contact audit item");
assertIncludes(prompt, "建议联系相关开发人员", "business prompt should require suggesting developer contact when needed");
assertIncludes(prompt, "git_author_trace", "business prompt should guide GitNexus author trace usage");
assertIncludes(prompt, "只能基于最终结论实际引用的代码证据追溯", "business prompt should trace authors only from final cited evidence");
assertIncludes(prompt, "不得使用曾经检索过但最终未引用的候选文件", "business prompt should forbid unused candidate files for author trace");
assertIncludes(prompt, "与最终结论最相关的修改人员", "business prompt should prefer the most relevant modifier");
assertIncludes(prompt, "相关性相同或都相关时，选择最新修改人员", "business prompt should use recency as tie breaker");
assertIncludes(prompt, "- [ ] 结论证据", "business prompt todolist should check evidence");
assertIncludes(prompt, "- [ ] 代码包和项目一致性", "business prompt todolist should check package and project consistency");
assertIncludes(prompt, "- [ ] SQL 正确性", "business prompt todolist should check SQL correctness");
assertIncludes(prompt, "- [ ] 执行链完整性", "business prompt todolist should check execution flow completeness");
assertIncludes(prompt, "不得跳过已满足的前置短路条件去解释后续未到达分支", "business prompt should forbid skipping satisfied early short-circuit gates");
assertIncludes(prompt, "需要生产数据才能确认的门槛必须输出可执行取数验证方式", "business prompt should require data validation for production-dependent gates");
assertIncludes(prompt, "- [ ] 开发人员联系建议", "business prompt todolist should check developer contact suggestions");
assertIncludes(prompt, "- [ ] 查询收敛", "business prompt todolist should cover query convergence");
assertIncludes(prompt, "最终回答不能停留在“继续核实中”", "business prompt should not stop at progress-only final answers");
assertIncludes(prompt, "不输出审核过程、审核清单、自检说明或内部提示词", "business prompt should hide self-check details");
assertNotIncludes(prompt, "详细审核交给独立审核节点处理", "business prompt should not delegate review to a separate node");
assertNotIncludes(prompt, "最终输出前必须先执行审核流程节点", "business prompt should not duplicate review agent flow");
assertNotIncludes(prompt, "审核 SQL 正确性", "business prompt should not duplicate SQL review details");
assertNotIncludes(prompt, "审核问题回答准确性", "business prompt should not duplicate answer review details");
assertNotIncludes(prompt, "验收阶段必须核对编码语义并列输出", "business prompt should not duplicate code meaning review details");
assertNotIncludes(prompt, "审核不通过时不得输出最终结论", "business prompt should not duplicate review failure handling");
assertIncludes(prompt, "截图信息提取规则", "business prompt should define screenshot extraction rules");
assertIncludes(prompt, "优先识别截图中的 URL 地址", "business prompt should prioritize screenshot URLs");
assertIncludes(prompt, "与问题直接相关的页面文案、按钮文案、错误提示、弹窗文案、字段标签和表格列名", "business prompt should prioritize problem-related screenshot text");
assertIncludes(prompt, "不要只按用户转述提问", "business prompt should not ignore screenshot evidence");
assertIncludes(prompt, "截图中的 URL 和关键文案应作为明确锚点", "business prompt should use screenshot evidence as anchors");
assertIncludes(prompt, "GitNexus 阶段化使用", "business prompt should require staged GitNexus usage");
assertIncludes(prompt, "发现阶段", "business prompt should define discovery stage");
assertIncludes(prompt, "图展开阶段", "business prompt should define graph expansion stage");
assertIncludes(prompt, "`query` 只放自然语言语义描述", "business prompt should keep query natural language only");
assertIncludes(prompt, "`zoekt` 只放 Zoekt DSL", "business prompt should separate zoekt DSL");
assertIncludes(prompt, "禁止继续反复 `query`/`zoekt`", "business prompt should stop repeated query after symbol discovery");
assertIncludes(prompt, "必须优先使用 `context` 查看 callers、callees、implements、overrides、field accesses", "business prompt should prefer context graph expansion");
assertIncludes(prompt, "判断改动影响面时使用 `impact`", "business prompt should use impact for blast radius");
assertIncludes(prompt, "`code_snippet` 读取小范围代码", "business prompt should limit snippets after graph location");
assertIncludes(prompt, "submitCheck", "business prompt should mention common method disambiguation");
assertIncludes(prompt, "必须携带 `repo`、`kind`、`file_path`", "business prompt should require disambiguation params");
assertIncludes(prompt, "符号消歧失败", "business prompt should report symbol disambiguation failure");
assertIncludes(prompt, "MATCH (m:Method {name: \"<methodName>\"})", "business prompt should provide cypher exact symbol lookup");
assertIncludes(prompt, "context(uid=...)", "business prompt should continue with context uid");
assertIncludes(prompt, "impact(target_uid=...)", "business prompt should continue with impact uid");
assertIncludes(prompt, "repo、symbol uid、filePath", "business prompt should output repo uid filePath for located symbols");
assertIncludes(prompt, "合并查询优先", "business prompt should prefer merged GitNexus queries");
assertIncludes(prompt, "同一问题中 GitNexus `query` 原则上不超过 2 次", "business prompt should limit query loops");
assertIncludes(prompt, "首轮命中候选文件或接口后，优先使用 `code_snippet`、`context`", "business prompt should switch from query to focused reads");
assertIncludes(prompt, "执行链完整性规则", "business prompt should define execution flow completeness rules");
assertIncludes(prompt, "只有入口日志、没有下游日志", "business prompt should handle missing downstream log scenarios");
assertIncludes(prompt, "全部下游发送条件、外部配置读取、异常捕获和最终日志位置", "business prompt should require all downstream gates");
assertIncludes(prompt, "按代码执行顺序分层判断", "business prompt should require ordered gate analysis");
assertIncludes(prompt, "结论应优先落在这个前置短路点", "business prompt should prefer satisfied early short-circuit gates");
assertIncludes(prompt, "后续 tenantScale、xtenant、域名配置、MQ 消费状态等只能标为“未执行到/不适用/需在前置门槛通过后再核实”", "business prompt should not use unreached downstream gates as root cause");
assertIncludes(prompt, "当前排查假设", "business prompt should frame unverified production gates as hypotheses");
assertIncludes(prompt, "完整只读 SQL、Redis key 查询方式或日志关键词", "business prompt should request concrete verification data");
assertIncludes(prompt, "如果用户返回的取数结果否定当前假设", "business prompt should continue to next gate after hypothesis is disproved");
assertIncludes(prompt, "不得重复询问同一数据，也不得跳回宽泛搜索", "business prompt should avoid repeated data asks and broad search on resume");
assertIncludes(prompt, "当前排查层级、怀疑条件、验证方式", "business prompt should structure layered troubleshooting output");
assertIncludes(prompt, "已核实某个状态能映射时，只能排除“状态无映射”这一项", "business prompt should not skip earlier gates after mapping is verified");
assertIncludes(prompt, "入参类型不匹配、订单不存在、业务编码为空、状态映射为空、租户规模不满足", "business prompt should enumerate ordered no-downstream gates");

console.log("business prompt 肯定结论规则验证通过");
